import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";

import { site } from "@/config/site";
import { JsonLd } from "@/components/JsonLd";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ClickEffectsOverlay } from "@/components/ClickEffectsOverlay";
import { Preloader } from "@/components/Preloader";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

import "./globals.css";
import { cn } from "@/lib/utils";

const display = Inter({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const code = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-code",
  display: "swap",
});

/* --------------------------------------------------------------------------
 * SEO — Next.js Metadata API.
 * Everything here is derived from src/config/site.ts.
 * ------------------------------------------------------------------------ */
export const metadata: Metadata = {
  metadataBase: new URL(site.url),

  title: {
    default: site.seo.title,
    template: site.seo.titleTemplate,
  },
  description: site.seo.description,
  keywords: [...site.seo.keywords],

  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  publisher: site.name,

  alternates: {
    canonical: "/",
  },

  openGraph: {
    type: "profile",
    locale: site.seo.locale,
    url: site.url,
    siteName: site.seo.title,
    title: site.seo.title,
    description: site.seo.description,
    firstName: site.firstName,
    /* The image itself is generated by src/app/opengraph-image.tsx. */
  },

  twitter: {
    card: "summary_large_image",
    title: site.seo.title,
    description: site.seo.description,
    creator: site.seo.twitterHandle ? `@${site.seo.twitterHandle}` : undefined,
    site: site.seo.twitterHandle ? `@${site.seo.twitterHandle}` : undefined,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  verification: site.seo.googleSiteVerification
    ? { google: site.seo.googleSiteVerification }
    : undefined,

  category: "technology",
  applicationName: site.seo.title,
  referrer: "origin-when-cross-origin",
  formatDetection: { email: false, address: false, telephone: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  /* Do NOT lock zoom — pinch-to-zoom is an accessibility requirement. */
  maximumScale: 5,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#09090b" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang={site.seo.lang}
      suppressHydrationWarning
      className={cn(display.variable, code.variable, "font-sans")}
    >
      <head>
        <JsonLd />

        {/* Entrance animations server-render at opacity:0. If JS never runs,
            this reveals them so the page is still readable. */}
        <noscript>
          <style>{`[style*="opacity:0"]{opacity:1!important;filter:none!important;transform:none!important}`}</style>
        </noscript>
      </head>
      <body className="relative min-h-dvh antialiased">
        {/* next-themes: injects its own pre-paint script (no flash) and is the
            source of truth the canvas/GSAP effects read for their colors. */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Keyboard users land here first. */}
          <a
            href="#main"
            className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-accent-600 focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-white"
          >
            Skip to content
          </a>

          <Preloader />

          <ClickEffectsOverlay />

          <Header />

          <main id="main" className="relative">
            {children}
          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
